"""End-of-day review.

The review has two responsibilities:

1. Produce a human-readable summary the dashboard can render.
2. Propose (never apply) strategy changes.

If ANTHROPIC_API_KEY is in the environment, the review is generated by
Claude; otherwise we fill a deterministic template with the same
numbers. Both paths return the same shape, so the dashboard does not
care which one ran.
"""
from __future__ import annotations
import os
import json
from typing import Optional
from datetime import date

from config import ANTHROPIC_KEY_ENV


_SYSTEM_PROMPT = """You are GreenLight Trader's End-of-Day reviewer.
You are paired with a rule-based engine; you do NOT make trading decisions.
Your job is to:
1. Summarize the day in plain English (≤120 words).
2. Identify any mistakes (rule violations, sizing errors, timing errors).
3. PROPOSE strategy changes if warranted — but flag clearly that they
   require backtest approval before being applied.
4. Set a green/yellow/red light for tomorrow based on the numbers given.

Always respond as compact JSON with keys:
summary, mistakes, proposed_changes, next_day_plan, light, light_reason.
Be conservative. The book is $1,000 — capital preservation comes first."""


def _template(payload: dict) -> dict:
    """Deterministic fallback used when no API key is present."""
    metrics = payload.get("metrics", {})
    today = payload.get("today_snapshot", {})
    trades_today = payload.get("trades_today", [])
    light = payload.get("status", {}).get("light", "green")
    light_reason = payload.get("status", {}).get("reason", "")

    bits = []
    bits.append(
        f"Equity ended at ${today.get('equity', 0):,.2f} "
        f"(daily PnL ${today.get('daily_pnl', 0):+,.2f}, "
        f"drawdown {today.get('drawdown', 0)*100:.2f}%)."
    )
    if trades_today:
        wins = [t for t in trades_today if t.get("pnl", 0) > 0]
        losses = [t for t in trades_today if t.get("pnl", 0) <= 0]
        bits.append(
            f"{len(trades_today)} trade(s) closed today: "
            f"{len(wins)} winning, {len(losses)} losing."
        )
    else:
        bits.append("No trades closed today.")
    bits.append(
        f"Backtest Sharpe {metrics.get('sharpe', 0):.2f}, "
        f"win rate {metrics.get('win_rate', 0)*100:.1f}%, "
        f"max DD {metrics.get('max_drawdown', 0)*100:.1f}%."
    )

    mistakes = []
    for t in trades_today:
        if t.get("exit_reason") == "stop" and abs(t.get("pnl", 0)) > 12:
            mistakes.append(
                f"{t['symbol']} stop-out larger than 1% account risk — review "
                "stop placement and ATR window."
            )

    proposed = []
    if metrics.get("win_rate", 0) and metrics["win_rate"] < 0.35 and metrics.get("n_trades", 0) > 20:
        proposed.append({
            "strategy": "momentum_breakout_v1",
            "change": "tighten volume_mult from 1.5 to 2.0",
            "reason": "low win rate suggests too many false breakouts",
            "status": "needs backtest approval",
        })
    if metrics.get("max_drawdown", 0) > 0.08:
        proposed.append({
            "strategy": "account-level",
            "change": "reduce max_risk_per_trade_pct from 1.0% to 0.75%",
            "reason": "drawdown approaching 10% hard stop",
            "status": "needs backtest approval",
        })

    return {
        "summary": " ".join(bits),
        "mistakes": mistakes,
        "proposed_changes": proposed,
        "next_day_plan": (
            "Run the standard pre-market scan, recompute regime, refresh signals. "
            "Honor the same risk caps."
        ),
        "light": light,
        "light_reason": light_reason,
        "source": "template",
    }


def _try_anthropic(payload: dict) -> Optional[dict]:
    key = os.environ.get(ANTHROPIC_KEY_ENV)
    if not key:
        return None
    try:
        import anthropic  # type: ignore
    except Exception:
        return None
    try:
        client = anthropic.Anthropic(api_key=key)
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=800,
            system=_SYSTEM_PROMPT,
            messages=[{
                "role": "user",
                "content": "Daily payload:\n" + json.dumps(payload, default=str)[:6000],
            }],
        )
        text = "".join(b.text for b in msg.content if getattr(b, "type", None) == "text")
        # Try to extract JSON; fall back to a wrap
        start, end = text.find("{"), text.rfind("}")
        if start >= 0 and end > start:
            try:
                parsed = json.loads(text[start:end + 1])
                parsed.setdefault("source", "anthropic")
                return parsed
            except json.JSONDecodeError:
                pass
        return {
            "summary": text[:600],
            "mistakes": [],
            "proposed_changes": [],
            "next_day_plan": "",
            "light": payload.get("status", {}).get("light", "green"),
            "light_reason": payload.get("status", {}).get("reason", ""),
            "source": "anthropic-unparsed",
        }
    except Exception as e:
        return {
            "summary": f"LLM review failed: {e}. Falling back to template.",
            "mistakes": [],
            "proposed_changes": [],
            "next_day_plan": "",
            "light": payload.get("status", {}).get("light", "green"),
            "light_reason": payload.get("status", {}).get("reason", ""),
            "source": "anthropic-error",
        }


def review(payload: dict) -> dict:
    out = _try_anthropic(payload)
    if out is None:
        out = _template(payload)
    out["review_date"] = date.today().isoformat()
    return out
